apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-peso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-peso
  template:
    metadata:
      labels:
        app: web-peso
    spec:
      containers:
        - name: web-peso
          image: alexandrebunn/conversao-peso:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-peso
spec:
  selector:
    app: web-peso
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
      protocol: TCP
  type: NodePort